name: 'action-upload-to-s3'
description: 'Recursively upload folder to S3 bucket'
author: 'core3'
branding:
  icon: 'crosshair'  
  color: 'green'
inputs:
  accessKeyId: 
    required: true
    description: 'AWS Access key id (short one)'
  secretAccessKey: 
    required: true
    description: 'AWS Secret access key  (long one)'
  awsBucket:
    required: true
    description: 'bucket name'
  s3Subfolder:
    required: true
    description: 'subfolder in bucket to upload data to'
  sourceFolder:
    required: true
    description: 'sourcefolder to upload'
  tags:
    required: true
    description: 'tags to set for uploaded files "Business Unit=core3&gitref=someverylongref"'
runs:
  using: 'node12'
  main: 'dist/index.js'
