name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14,16]
    steps:
      - uses: actions/checkout@v2
      - name: upload-folder
        uses: ./        
        with:
          accessKeyId: ${{ secrets.AWS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          awsBucket: core3.static.releases
          s3Subfolder: test-uploads
          sourceFolder: '__tests__/fixtures/folder_to_upload'
          tags: 'Business Unit=core3&gitref=${{github.ref}}'
        env:
          GITHUB_TOKEN: ${{ github.token }}
